name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: yarn install --force

      - name: Build project
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: paddocks-build
          path: |
            dist/
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: paddocks-build

      - name: Deploy files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: 'dist/*'
          target: 'web/www/paddocks'
          overwrite: true

  restart-service:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Execute pm2 restart
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: yarn && pm2 restart paddocks
